<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\EntryForm;
use app\models\ResetForm;
use app\models\User;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionReset()
    {
        // authenticate that this is a link generated by our system
        $paras = Yii::$app->request->get();
        if(!isset($paras['name']) || !isset($paras['code']))
            return $this->goHome();

        $user = User::find()->where(['name' => $paras['name']])->one();
        if($user->password != $paras['code'])
            return $this->goHome();

        $model = new ResetForm();
        return $this->render('reset', ['model' => $model]);
    }
    public function actionUpdate()
    {
        $paras = Yii::$app->request->post();       
        $user = User::find()->where(['name' => $paras['ResetForm']['name']])->one();
        $user->password = md5($paras['ResetForm']['password'], false);
        $user->update();
        return 'succees';
        //$user
    }
    public function goHome()
    {
        return $this->render('index');
    }
    public function actionAbout()
    {
        return $this->render('about');
    }

}
